name: Gamer
version: 1.0
author: Joebaria
main: xyz.joebaria.Gamer.Gamer
commands:
  destroy:
    description: kill essentially
    usage: /destroy <player>
    permission: op
    permission-message: gamer you can't
  nick:
    description: nickname
    usage: /nick <nickname>
  trade:
    description: trade with other players item in main hands
    useage: /trade <target_player>
  confirm:
    description: confirm trades
    useage: /confirm